// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/CallToActio.tsx";
import * as $$$$$$1 from "./sections/Footer.tsx";
import * as $$$$$$2 from "./sections/Header/Header.tsx";
import * as $$$$$$3 from "./sections/ItWorks.tsx";
import * as $$$$$$4 from "./sections/MainBox/LargeDisplayCard.tsx";
import * as $$$$$$5 from "./sections/MainBox/SmallDisplatBox.tsx";
import * as $$$$$$6 from "./sections/Navbar/Navbar.tsx";
import * as $$$$$$7 from "./sections/Testimonial.tsx";
import * as $$$$$$8 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/CallToActio.tsx": $$$$$$0,
    "site/sections/Footer.tsx": $$$$$$1,
    "site/sections/Header/Header.tsx": $$$$$$2,
    "site/sections/ItWorks.tsx": $$$$$$3,
    "site/sections/MainBox/LargeDisplayCard.tsx": $$$$$$4,
    "site/sections/MainBox/SmallDisplatBox.tsx": $$$$$$5,
    "site/sections/Navbar/Navbar.tsx": $$$$$$6,
    "site/sections/Testimonial.tsx": $$$$$$7,
    "site/sections/Theme/Theme.tsx": $$$$$$8,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
